% Auto generated function to simulate the generated HDL code using cosimulation
% 
% Generated by MATLAB 8.4 and HDL Coder 3.5

function [c_out,state_store] = hdl_matmul_cosim(a_in,b_in)

coder.extrinsic('hdl_matmul_sysobj_cosim');
coder.extrinsic('hdlverifier.assert');
coder.extrinsic('hdlverifier.Delay');
coder.extrinsic('step');

% Declare persistent variables
persistent initialized;

% Initialize persistent variables
if isempty(initialized)
   initialized = true;
end

% Call the original MATLAB function to get reference signal
[ref_c_out,ref_state_store] = hdl_matmul(a_in,b_in);

% Run cosimulation
[c_out,state_store] = hdl_matmul_sysobj_cosim(a_in,b_in);

% Verify the cosimulation output
hdlverifier.assert(c_out,ref_c_out,'c_out');
hdlverifier.assert(state_store,ref_state_store,'state_store');

