% Auto generated function to launch ModelSim simulator
% 
% Generated by MATLAB 8.4 and HDL Coder 3.5

function launch_hdl_matmul_cosim
% Make sure there is no HDL simulator using the communication channel
pid = pingHdlSim(1);
if pid > 0
   error('hdlverifier:mlhdlc:HDLServerExist','Another instance of HDL simulator exists. Close all HDL simulator instances and try again');
end
currentdir = cd('/home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/hdlsrc');
onCleanupObj = onCleanup(@() cd(currentdir));
% Pre-sim TCL commands
tclCmds = { ...
    'vlib work',...% Compile the generated code
    'vcom hdl_matmul_pkg.vhd',...
    'vcom hdl_matmul.vhd',...
    'vsimmatlabsysobj -novopt work.hdl_matmul',...% Initiate cosimulation
    'set UserTimeUnit ns',...% Set simulation time unit
    'puts ""',...
    'puts "Ready for cosimulation..."',...
};
% Launch HDL simulator
vsim('tclstart',tclCmds,'runmode','Batch');
