% Function localRecompile_hdl_matmul_cosim recreates a MEX-function hdl_matmul_cosim_mex from MATLAB function hdl_matmul_cosim
% Generated by MATLAB 8.4 and HDL Coder 3.5
function localRecompile_hdl_matmul_cosim

load('/home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/cosim/localCodegenArgs_hdl_matmul_cosim');

codegen -args exInputs -o '/home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/cosim/hdl_matmul_cosim_mex' hdl_matmul_cosim;

