# Generated by MATLAB 8.4 and HDL Verifier 4.5
# For internal use only

load_package flow
project_new -overwrite hdl_matmul_fil
set_global_assignment -name FAMILY  {Cyclone IV E}
set_global_assignment -name DEVICE  {EP4CE22F17C6}
set_global_assignment -name CYCLONEII_OPTIMIZATION_TECHNIQUE SPEED
set_global_assignment -name PHYSICAL_SYNTHESIS_REGISTER_RETIMING ON
set_global_assignment -name PHYSICAL_SYNTHESIS_COMBO_LOGIC ON
set_global_assignment -name PHYSICAL_SYNTHESIS_REGISTER_DUPLICATION ON
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/hdlsrc/hdl_matmul_pkg.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/hdlsrc/hdl_matmul.vhd
set_global_assignment -name USE_TIMEQUEST_TIMING_ANALYZER ON
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWClkMgr.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWAJTAG.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/FILPKTBuilder.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWDPRAM.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWRXBuffer.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWTXBuffer.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWArbiter.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/FILSYNCBuffer.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfRXDecoder.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWRotateRight.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWMuxReg.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfRXUnpack.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfRX.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfTX.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfRXCtrl.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfTXCtrl.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIfCtrl.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/MWChIf.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/FILCommLayer.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/FILCmdProc.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/hdl_matmul_wrapper.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/FILCore.vhd
set_global_assignment -name VHDL_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/hdl_matmul_fil.vhd
source /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/hdl_matmul_fil.qsf
set_global_assignment -name SDC_FILE /home/vipinsoni/MTP/hdl_coder_matlab/codegen/hdl_matmul/fil/hdl_matmul_fil/filsrc/hdl_matmul_fil.sdc
set_global_assignment -name USE_TIMEQUEST_TIMING_ANALYZER ON
set_global_assignment -name TOP_LEVEL_ENTITY hdl_matmul_fil
execute_flow -analysis_and_elaboration
project_close
