/*
 * File: multiplication_fixpt.c
 *
 * MATLAB Coder version            : 2.7
 * C/C++ source code generated on  : 13-Feb-2018 17:53:04
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "multiplication_fixpt.h"

/* Function Definitions */

/*
 * Arguments    : unsigned char a
 *                unsigned char b
 * Return Type  : unsigned char
 */
unsigned char multiplication_fixpt(unsigned char a, unsigned char b)
{
  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  /*                                                                           % */
  /*            Generated by MATLAB 8.4 and Fixed-Point Designer 4.3           % */
  /*                                                                           % */
  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  return (unsigned char)((unsigned char)((unsigned int)a * b) & 63);
}

/*
 * File trailer for multiplication_fixpt.c
 *
 * [EOF]
 */
