% Auto generated wrapper function for FPGA-in-the-Loop System object

% Generated by MATLAB 8.4 and HDL Coder 3.5

function [c_out,state_store] = hdl_matmul_sysobj_fil(a_in,b_in)

% Declare persistent variables
persistent fil_sys_obj;

if isempty(fil_sys_obj)
   % Instantiate FPGA-in-the-Loop System object
   fil_sys_obj = class_hdl_matmul_sysobj;
end

[c_out,state_store] = step(fil_sys_obj,a_in,b_in);

